language: java
sudo: false
addons:
  firefox: "53.0"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || echo Without Xvfb
  - sleep 3
script:
  - RUN_PARAMS="-Djunit.browser=open"
  - TEST_PARAMS=""
  - if type firefox; then RUN_PARAMS="-Djunit.browser=firefox"; fi
  - if type xdg-open; then echo On linux; else echo On Mac; TEST_PARAMS="-DskipTests"; fi
  - mvn clean install $RUN_PARAMS $TEST_PARAMS
os:
  - linux
  - osx
