/**
 * The MIT License (MIT)
 *
 * Copyright (C) 2013-2020 Jaroslav Tulach <jaroslav.tulach@apidesign.org>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.apidesign.demo.minesweeper.js;

import net.java.html.js.JavaScriptBody;

public final class RandomGenerator {
    private Object[] randoms;
    private int at;

    public int nextInt(int upto) {
        refreshRandoms(false);
        var next = randoms[at++];
        var value = ((Number) next).doubleValue() * upto;
        return (int) value;
    }

    private void refreshRandoms(boolean force) {
        if (force || randoms == null || at == randoms.length) {
            randoms = generateRandomNumbers(128);
            at = 0;
        }
    }

    @JavaScriptBody(args = { "count" }, body = """
        var arr = [];
        while (count-- > 0) {
            arr.push(Math.random());
        }
        return arr;
        """
    )
    private static native Object[] generateRandomNumbers(int count);

    /** Reinitializes the generator to provided seed.
     *
     * @param seed the seed generated by {@link #getSeed()}
     * @throws NumberFormatException if the seed isn't valid
     * @see #getSeed
     */
    public void seedTo(String seed) throws NumberFormatException {
        if (seed.length() == 0) {
            refreshRandoms(true);
            return;
        }
        var num = seed.split("X");
        var arr = new Object[num.length];
        for (var i = 0; i < num.length; i++) {
            try {
                arr[i] = Double.valueOf(num[i]);
            } catch (NumberFormatException ex) {
                throw new NumberFormatException("Cannot parse " + num[i]);
            }
        }
        randoms = arr;
        at = 0;
    }

    /** Takes the seed that was used to generate the last sequence
     * of random numbers. The string can then be sent to {@link #seedTo}
     * to <em>replay</em> the sequence again.
     *
     * @return textual representation of the sequence
     * @see #seedTo
     */
    public String getSeed() {
        var sb = new StringBuilder();
        var sep = "";
        for (var i = 0; i < at; i++) {
            if (randoms[i] instanceof Number next) {
                sb.append(sep);
                sb.append(next.doubleValue());
                sep = "X";
            } else {
                return "";
            }
        }
        return sb.toString();
    }
}
