/**
 * The MIT License (MIT)
 *
 * Copyright (C) 2013-2020 Jaroslav Tulach <jaroslav.tulach@apidesign.org>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.apidesign.demo.minesweeper.js;

import net.java.html.js.JavaScriptBody;

public final class RandomGenerator {
    private long seed;
    private long[] current;
    private static final long MUL = 0x5DEECE66DL;
    private static final long ADD = 0xBL;
    private static final long MASK = (1L << 48) - 1;

    public RandomGenerator() {
        seedTo(null);
    }

    public int nextInt(int upto) {
        if ((upto & -upto) == upto)  // i.e., n is a power of 2
            return (int)((upto * (long)next(31, current)) >> 31);

        int bits, val;
        do {
            bits = next(31, current);
            val = bits % upto;
        } while (bits - val + (upto-1) < 0);
        return val;
    }

    private static int next(int bits, long[] holder) {
        var oldseed = holder[0];
        var nextseed = (oldseed * MUL + ADD) & MASK;
        holder[0] = nextseed;
        return (int)(nextseed >>> (48 - bits));
    }

    /** Reinitializes the generator to provided seed.
     *
     * @param setTo the seed generated by {@link #getSeed()} or {@code null} to reset to random value
     * @throws NumberFormatException if the seed isn't valid
     * @see #getSeed
     */
    public void seedTo(String setTo) throws NumberFormatException {
        if (setTo == null || setTo.length() == 0) {
            var setSeed = new long[1];
            setSeed[0] = now();
            this.seed = next(31, setSeed);
        } else if (setTo.startsWith("m")) {
            this.seed = Long.parseLong(setTo.substring(1), 16);
        } else {
            throw new NumberFormatException(setTo);
        }
        assert this.seed >= 0;
        this.current = new long[] { this.seed };
    }

    /** Takes the seed that was used to generate the last sequence
     * of random numbers. The string can then be sent to {@link #seedTo}
     * to <em>replay</em> the sequence again.
     *
     * @return textual representation of the sequence
     * @see #seedTo
     */
    public String getSeed() {
        return "m" + Long.toHexString(seed);
    }

    @JavaScriptBody(args = {  }, body = """
    return new Date().getTime();
    """)
    private static long now() {
        return System.currentTimeMillis();
    }
}
